/**
 * Swipe Shop UI — the deck, the gestures, and the profile page.
 * All state is local; the only network activity is the outbound link when
 * the user chooses to open a product on its home shopping site.
 */

import {
  CATALOG,
  CATEGORY_LABELS,
  PLATFORM_LABELS,
  PRICE_BAND_LABELS,
  platformLabel,
  priceBand,
  productFeatures,
  productUrl,
} from "./catalog.js";
import {
  createProfile,
  recordSwipe,
  undoLastSwipe,
  tasteSummary,
  profileStrength,
  shortlist,
} from "./profile.js";
import { buildDeck } from "./deck.js";
import { loadProfile, saveProfile, clearProfile } from "./store.js";
import { APP_VERSION, buildDateLabel } from "./version.js";
import { scoreProduct } from "./profile.js";
import { liveEnabled, searchSummaries, fetchDetail, steeringQueries, MAP_QUERIES } from "./feed.js";

const $ = (sel) => document.querySelector(sel);
const BY_ID = new Map(CATALOG.map((p) => [p.id, p]));
const SWIPE_X = 100; // px of drag that commits a like/nope
const SWIPE_Y = 110; // px of upward drag that commits a love

// Real listings can contain any characters — escape before innerHTML.
const esc = (s) =>
  String(s ?? "").replace(/[&<>"']/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

let catalog = CATALOG;
let profile = loadProfile();
let filter = null; // {feature, label} — tag-focus mode; null = free roam
let deck = buildDeck(catalog, profile);
let busy = false; // true while a card is flying out

/** The catalog the deck draws from — narrowed to one trait in filter mode. */
function activeCatalog() {
  if (!filter) return catalog;
  return catalog.filter((p) => productFeatures(p).includes(filter.feature));
}

function applyFilter(feature, label) {
  // Tapping the active tag again unchecks it — back to free roam.
  if (filter && filter.feature === feature) return clearFilter();
  filter = { feature, label };
  $("#filter-label").textContent = label;
  $("#filter-bar").hidden = false;
  deck = buildDeck(activeCatalog(), profile);
  renderStack();
  showTab("deck");
}

function clearFilter() {
  filter = null;
  $("#filter-bar").hidden = true;
  deck = buildDeck(activeCatalog(), profile);
  renderStack();
}

/**
 * Swap in the real product feed if the site ships one (catalog.json is
 * generated by the refresh workflow from live shopping data). The bundled
 * sample catalog keeps working offline and before the first refresh.
 * Old catalog entries stay in BY_ID so an existing shortlist keeps resolving.
 */
/**
 * A card is only worth swiping if the user can decide on the spot:
 * a real photo gallery (more than one picture) AND something to read
 * (specs, description, or feature bullets). Anything shallower just
 * pushes the user out to the browser.
 */
function isInteractive(p) {
  return (p.images?.length ?? 0) > 1 && Boolean(p.specs?.length || p.description || p.features?.length);
}

async function loadRealCatalog() {
  try {
    const res = await fetch("./catalog.json", { cache: "no-cache" });
    if (!res.ok) return;
    const doc = await res.json();
    if (!Array.isArray(doc.products)) return;
    const interactive = doc.products.filter(isInteractive);
    if (interactive.length < 12) return;
    catalog = interactive;
    for (const p of catalog) BY_ID.set(p.id, p);
    deck = buildDeck(activeCatalog(), profile);
    renderStack();
  } catch {
    /* offline or malformed feed — the sample catalog stands in */
  }
}

// ------------------------------------------------ live feed (map + upgrades)
//
// Tier 0: a broad, cheap MAP of candidate items (search summaries — text
// and one thumbnail). Tier 2: full details fetched just-in-time, ONLY for
// the candidates the user's own swipes rank highly. Every ~dozen swipes,
// the top taste features spawn fresh searches, so the pool is effectively
// all of eBay rather than anything pre-fetched.

const liteMap = new Map(); // id → lite candidate awaiting a possible upgrade
let upgradesUsed = 0;
const UPGRADE_CAP = 120; // per session — keeps API use honest
let upgrading = false;

const swipedIds = () => new Set(profile.swipes.map((s) => s.productId));

async function loadMapQuery(spec) {
  try {
    const seen = swipedIds();
    for (const item of await searchSummaries(spec, 50)) {
      if (!BY_ID.has(item.id) && !seen.has(item.id) && !liteMap.has(item.id)) {
        liteMap.set(item.id, item);
      }
    }
  } catch {
    /* one bad query never matters */
  }
}

async function startLiveFeed() {
  if (!liveEnabled()) return;
  const sweep = [...MAP_QUERIES].sort(() => Math.random() - 0.5);
  for (let i = 0; i < sweep.length; i += 6) {
    await Promise.allSettled(sweep.slice(i, i + 6).map(loadMapQuery));
    upgradeTick();
    await new Promise((r) => setTimeout(r, 700));
  }
}

/**
 * Upgrade the most promising lite candidates to full interactive cards —
 * when the deck is running low, or when a candidate outranks what's
 * already near the top of the deck (taste alignment = dig deeper).
 */
async function upgradeTick() {
  if (!liveEnabled() || upgrading || upgradesUsed >= UPGRADE_CAP || !liteMap.size) return;
  const seen = swipedIds();
  const remaining = deck.length;
  const ranked = [...liteMap.values()]
    .filter((p) => !seen.has(p.id))
    .sort((a, b) => scoreProduct(profile, b) - scoreProduct(profile, a));
  if (!ranked.length) return;
  const deckRef = deck[2] ? scoreProduct(profile, deck[2]) : 0;
  const need = remaining < 30;
  if (!need && scoreProduct(profile, ranked[0]) <= deckRef) return;

  upgrading = true;
  try {
    for (const c of ranked.slice(0, 4)) {
      liteMap.delete(c.id);
      try {
        const full = await fetchDetail(c);
        upgradesUsed++;
        if (isInteractive(full)) {
          catalog.push(full);
          BY_ID.set(full.id, full);
        }
      } catch { /* skip this one */ }
    }
    if (deck.length === 0) {
      deck = buildDeck(activeCatalog(), profile);
      renderStack();
    }
  } finally {
    upgrading = false;
  }
}

/** Swipe-driven steering: taste features become brand-new live searches. */
function steerFeed() {
  if (!liveEnabled()) return;
  for (const spec of steeringQueries(tasteSummary(profile))) {
    loadMapQuery(spec).then(() => upgradeTick());
  }
}

// ---------------------------------------------------------------- rendering

function heroGradient(p) {
  return `linear-gradient(160deg, hsl(${p.hue} 85% 88%), hsl(${(p.hue + 45) % 360} 80% 76%))`;
}

/** Every photo a product has (real listings may carry a gallery). */
function imagesOf(p) {
  if (Array.isArray(p.images) && p.images.length) return p.images;
  return p.image ? [p.image] : [];
}

/** A filterable chip; shows as checked (✕ to uncheck) when it's the active filter. */
function chipEl(feature, label, extra = "") {
  const on = filter && filter.feature === feature;
  return `<span class="chip${extra ? ` ${extra}` : ""}${on ? " chip-on" : ""}"
    data-feature="${esc(feature)}">${esc(label)}${on ? " ✕" : ""}</span>`;
}

function cardEl(product, depth) {
  const card = document.createElement("article");
  card.className = "card";
  card.dataset.depth = String(depth);
  card.dataset.id = product.id;
  if (depth === 0) card.classList.add("is-top");

  // Tappable chips: data-feature enters filter mode for that trait;
  // the active one is highlighted and tapping it again unchecks it.
  const band = priceBand(product.price);
  const tags = [
    chipEl(`cat:${product.category}`, CATEGORY_LABELS[product.category] ?? product.category, "chip-cat"),
    chipEl(`price:${band}`, PRICE_BAND_LABELS[band], "chip-cat"),
    ...product.tags.map((t) => chipEl(`tag:${t}`, t)),
  ].join("");
  // Real listings carry photos; the emoji stays behind them as the loading /
  // error fallback. The photo is never cropped: it shows whole (contain)
  // over a blurred, zoomed copy of itself that fills the card edge-to-edge.
  const imgs = imagesOf(product);
  const art = imgs.length
    ? `<img class="card-img-bg" src="${esc(imgs[0])}" alt="" aria-hidden="true"
         onerror="this.remove()" draggable="false" />
       <img class="card-img" src="${esc(imgs[0])}" alt="" loading="lazy"
         onerror="this.remove()" draggable="false" />`
    : "";
  const dots = imgs.length > 1
    ? `<span class="hero-dots">${imgs
        .map((_, i) => `<i class="hero-dot${i === 0 ? " is-on" : ""}"></i>`).join("")}</span>`
    : "";
  const sub = [product.brand, product.blurb].filter(Boolean).join(" · ");
  card.innerHTML = `
    <div class="card-hero" style="background:${heroGradient(product)}">
      <span>${product.emoji ?? "🛍"}</span>
      ${art}
      ${dots}
      <span class="card-platform">${esc(platformLabel(product))}</span>
      <span class="card-price">$${product.price}</span>
      <span class="card-stamp stamp-like">LIKE</span>
      <span class="card-stamp stamp-nope">NOPE</span>
      <span class="card-stamp stamp-love">NEED IT</span>
    </div>
    <div class="card-overlay">
      <h2 class="card-title"><a class="card-title-link" href="${esc(productUrl(product))}"
        target="_blank" rel="noopener noreferrer" title="See it on ${esc(platformLabel(product))}">${esc(product.title)}</a></h2>
      ${sub ? `<p class="card-sub">${esc(sub)}</p>` : ""}
      <div class="card-tags">${tags}</div>
    </div>`;
  // Adaptive fit: photos shaped close to the card go edge-to-edge (cover,
  // small crop); very mismatched shapes stay whole over the blur fill.
  const img = card.querySelector(".card-img");
  if (img) {
    const refit = () => {
      const frame = img.clientWidth / img.clientHeight;
      const nat = img.naturalWidth / img.naturalHeight;
      if (!frame || !nat) return;
      const ratio = nat > frame ? nat / frame : frame / nat;
      img.classList.toggle("is-cover", ratio <= 1.35);
    };
    img.addEventListener("load", refit);
    if (img.complete) refit();
  }
  return card;
}

function renderStack() {
  const stack = $("#stack");
  stack.textContent = "";
  const visible = deck.slice(0, 3);
  // Deepest first so the top card is last in DOM (highest paint order).
  for (let i = visible.length - 1; i >= 0; i--) {
    stack.appendChild(cardEl(visible[i], i));
  }
  const empty = deck.length === 0;
  $("#deck-empty").hidden = !empty;
  $("#actions").hidden = empty;
  if (empty) {
    $("#deck-empty-title").textContent = filter
      ? `That’s every “${filter.label}” item`
      : "You’ve swiped the whole catalog";
    $("#deck-empty-text").textContent = filter
      ? "Clear the filter to keep browsing everything else."
      : "Your shopping profile is fully trained on this feed. Check your profile and shortlist — or wipe the slate and start again.";
    $("#empty-clear-filter").hidden = !filter;
    $("#empty-reset").hidden = !!filter;
  }
  if (!empty) attachDrag(stack.lastElementChild);
  renderChrome();
}

function renderChrome() {
  const { label, pct } = profileStrength(profile);
  $("#strength-label").textContent = label;
  $("#strength-fill").style.width = `${pct}%`;

  const picks = shortlist(profile, BY_ID);
  const badge = $("#shortlist-count");
  badge.hidden = picks.length === 0;
  badge.textContent = String(picks.length);

  $("#deck-progress").textContent = deck.length
    ? `${deck.length} of ${activeCatalog().length} left${filter ? ` in “${filter.label}”` : ""}`
    : "";

  $("#act-undo").disabled = profile.swipes.length === 0;
  const top = deck[0];
  const open = $("#act-open");
  if (top) open.href = productUrl(top);
}

// ------------------------------------------------------------------- swiping

function commitSwipe(verdict) {
  const product = deck[0];
  if (!product || busy) return;
  busy = true;

  // The user has already seen the cards peeking out of the stack — keep them
  // in place after the rebuild so the taste algorithm's reordering happens
  // beneath the visible cards, never as a jarring swap in front of the user.
  const pinned = deck.slice(1, 3).map((p) => p.id);

  recordSwipe(profile, product, verdict);
  saveProfile(profile);

  const top = $("#stack .is-top");
  if (top) {
    const fly =
      verdict === "nope" ? "translate(-130%, -6%) rotate(-24deg)"
      : verdict === "love" ? "translate(0, -140%) rotate(4deg)"
      : "translate(130%, -6%) rotate(24deg)";
    top.classList.add("is-flying");
    top.style.transform = fly;
    // Promote the cards underneath immediately so the stack feels alive.
    for (const card of document.querySelectorAll("#stack .card:not(.is-flying)")) {
      const depth = Number(card.dataset.depth) - 1;
      card.dataset.depth = String(Math.max(0, depth));
      card.classList.add("is-restacking");
    }
  }

  setTimeout(() => {
    busy = false;
    deck = buildDeck(activeCatalog(), profile);
    const front = pinned.map((id) => deck.find((p) => p.id === id)).filter(Boolean);
    deck = [...front, ...deck.filter((p) => !pinned.includes(p.id))];
    renderStack();
    const n = profile.swipes.length;
    if (n > 0 && n % 10 === 0) toast(`Profile sharpened — the feed just reordered around your taste (${n} swipes)`);
    if (n > 0 && n % 12 === 0) steerFeed();
    upgradeTick();
  }, 300);
}

function undo() {
  if (busy) return;
  const undone = undoLastSwipe(profile, BY_ID);
  if (!undone) return;
  saveProfile(profile);
  deck = buildDeck(activeCatalog(), profile);
  // Put the undone product back on top so the user sees what they got back.
  const i = deck.findIndex((p) => p.id === undone.productId);
  if (i > 0) deck.unshift(deck.splice(i, 1)[0]);
  renderStack();
}

function attachDrag(card) {
  if (!card) return;
  let startX = 0, startY = 0, dx = 0, dy = 0, dragging = false, pointerId = null;
  let downTarget = null; // element under the finger at press time

  const stamps = {
    like: card.querySelector(".stamp-like"),
    nope: card.querySelector(".stamp-nope"),
    love: card.querySelector(".stamp-love"),
  };

  card.addEventListener("pointerdown", (e) => {
    if (busy || e.button !== 0) return;
    // A press that starts on a link is a click-through to the store, not a
    // drag: capturing the pointer here would retarget the click at the card
    // and kill the navigation.
    if (e.target.closest("a")) return;
    downTarget = e.target;
    dragging = true;
    pointerId = e.pointerId;
    startX = e.clientX;
    startY = e.clientY;
    card.setPointerCapture(pointerId);
    card.classList.remove("is-settling");
  });

  card.addEventListener("pointermove", (e) => {
    if (!dragging || e.pointerId !== pointerId) return;
    dx = e.clientX - startX;
    dy = e.clientY - startY;
    card.style.transform = `translate(${dx}px, ${dy}px) rotate(${dx * 0.07}deg)`;
    const up = Math.max(0, -dy);
    const loveIntent = up > Math.abs(dx) * 1.2;
    stamps.like.style.opacity = loveIntent ? 0 : Math.min(1, Math.max(0, dx) / SWIPE_X);
    stamps.nope.style.opacity = loveIntent ? 0 : Math.min(1, Math.max(0, -dx) / SWIPE_X);
    stamps.love.style.opacity = loveIntent ? Math.min(1, up / SWIPE_Y) : 0;
  });

  const release = (e) => {
    if (!dragging || e.pointerId !== pointerId) return;
    dragging = false;
    const up = -dy;
    const loveIntent = up > Math.abs(dx) * 1.2 && up > SWIPE_Y;
    if (loveIntent) return commitSwipe("love");
    if (dx > SWIPE_X) return commitSwipe("like");
    if (dx < -SWIPE_X) return commitSwipe("nope");
    // Barely moved — that's a tap. A chip enters tag-filter mode; the info
    // overlay opens the details; on the photo, side thirds flip pictures
    // and the middle opens the details.
    if (Math.abs(dx) < 8 && Math.abs(dy) < 8) {
      const product = BY_ID.get(card.dataset.id);
      const chip = downTarget?.closest?.(".chip[data-feature]");
      if (product && chip) {
        applyFilter(chip.dataset.feature, chip.textContent.trim());
      } else if (product) {
        const overlay = card.querySelector(".card-overlay").getBoundingClientRect();
        if (e.clientY >= overlay.top) {
          openDetail(product);
        } else {
          const r = card.getBoundingClientRect();
          const rel = (e.clientX - r.left) / r.width;
          if (rel < 1 / 3) cycleHero(card, product, -1);
          else if (rel > 2 / 3) cycleHero(card, product, +1);
          else openDetail(product);
        }
      }
    }
    // Spring back.
    card.classList.add("is-settling");
    card.style.transform = "";
    for (const s of Object.values(stamps)) s.style.opacity = 0;
    dx = dy = 0;
  };
  card.addEventListener("pointerup", release);
  card.addEventListener("pointercancel", release);
}

// -------------------------------------------------- photo gallery & details

function cycleHero(card, product, dir) {
  const imgs = imagesOf(product);
  if (imgs.length < 2) return;
  const idx = (((Number(card.dataset.imgIdx ?? 0) + dir) % imgs.length) + imgs.length) % imgs.length;
  card.dataset.imgIdx = String(idx);
  for (const img of card.querySelectorAll(".card-img, .card-img-bg")) img.src = imgs[idx];
  card.querySelectorAll(".hero-dot").forEach((d, i) => d.classList.toggle("is-on", i === idx));
}

function openDetail(product) {
  const imgs = imagesOf(product);
  const hero = imgs.length
    ? `<img class="card-img-bg" src="${esc(imgs[0])}" alt="" aria-hidden="true" onerror="this.remove()" />
       <img src="${esc(imgs[0])}" alt="" onerror="this.remove()" />`
    : `<span class="detail-emoji">${product.emoji ?? "🛍"}</span>`;
  const extra = imgs.slice(1)
    .map((u) => `<img class="detail-extra" src="${esc(u)}" alt="" loading="lazy" onerror="this.remove()" />`)
    .join("");
  const features = Array.isArray(product.features) && product.features.length
    ? `<ul class="detail-features">${product.features.map((f) => `<li>${esc(f)}</li>`).join("")}</ul>`
    : "";
  const specs = Array.isArray(product.specs) && product.specs.length
    ? `<div class="detail-specs"><h3>Specifications</h3>${product.specs
        .map((s) => `<div class="about-row"><span>${esc(s.name)}</span><b>${esc(s.value)}</b></div>`)
        .join("")}</div>`
    : "";
  const reviews = Array.isArray(product.reviews) && product.reviews.length
    ? `<div class="detail-specs"><h3>What buyers say</h3>${product.reviews
        .map((r) => `<div class="detail-review">
          <p class="detail-review-head"><span class="detail-review-stars">${"★".repeat(Math.max(0, Math.min(5, Math.round(r.rating ?? 0))))}</span> ${esc(r.title ?? "")}</p>
          <p class="detail-review-text">${esc(r.text ?? "")}</p>
        </div>`).join("")}</div>`
    : "";
  $("#detail-body").innerHTML = `
    <div class="detail-hero" style="background:${heroGradient(product)}">${hero}</div>
    <div class="detail-info">
      <h2>${esc(product.title)}</h2>
      <p class="detail-meta">${esc([product.brand, platformLabel(product)].filter(Boolean).join(" · "))} · <b>$${product.price}</b></p>
      ${product.blurb ? `<p class="detail-blurb">${esc(product.blurb)}</p>` : ""}
      <div class="card-tags">
        ${chipEl(`cat:${product.category}`, CATEGORY_LABELS[product.category] ?? product.category, "chip-cat")}
        ${chipEl(`price:${priceBand(product.price)}`, PRICE_BAND_LABELS[priceBand(product.price)], "chip-cat")}
        ${product.tags.map((t) => chipEl(`tag:${t}`, t)).join("")}
      </div>
      <a class="btn btn-primary detail-shop" href="${esc(productUrl(product))}"
        target="_blank" rel="noopener noreferrer">Shop on ${esc(platformLabel(product))} ↗</a>
      ${product.description ? `<p class="detail-desc">${esc(product.description)}</p>` : ""}
      ${features}
      ${specs}
      ${reviews}
      ${extra}
    </div>`;
  $("#detail-backdrop").hidden = false;
  $("#detail-backdrop").querySelector(".detail-sheet").scrollTop = 0;
  document.body.style.overflow = "hidden";
}

function closeDetail() {
  $("#detail-backdrop").hidden = true;
  document.body.style.overflow = "";
}

// ------------------------------------------------------------------- profile

function traitLabel(kind, value) {
  if (kind === "cat") return CATEGORY_LABELS[value] ?? value;
  if (kind === "platform") return PLATFORM_LABELS[value] ?? value;
  if (kind === "price") return PRICE_BAND_LABELS[value] ?? value;
  return value;
}

const TRAIT_GROUPS = [
  ["word", "Words you gravitate to"],
  ["tag", "Styles & vibes"],
  ["cat", "Categories"],
  ["brand", "Brands"],
  ["price", "Price comfort zone"],
  ["platform", "Where you like to shop"],
];

function traitRows(entries, kind, avoid = false) {
  return entries
    .map(({ value, affinity }) => {
      const pct = Math.round(Math.abs(affinity) * 100);
      return `<div class="trait">
        <span class="trait-name">${traitLabel(kind, value)}</span>
        <span class="trait-bar"><span class="trait-fill${avoid ? " is-avoid" : ""}" style="width:${pct}%"></span></span>
        <span class="trait-pct">${pct}%</span>
      </div>`;
    })
    .join("");
}

function renderProfile() {
  const body = $("#profile-body");
  const summary = tasteSummary(profile);
  const { totals } = summary;
  const picks = shortlist(profile, BY_ID);

  const statsPanel = `<div class="panel">
    <h2>Your shopping profile</h2>
    <p class="panel-sub">Built entirely from your swipes, stored only on this device.
       The more you swipe, the sharper the Discover feed gets.</p>
    <div class="stat-row">
      <div class="stat"><b>${totals.all}</b><span>swipes</span></div>
      <div class="stat"><b>${totals.like}</b><span>liked</span></div>
      <div class="stat"><b>${totals.love}</b><span>need it</span></div>
      <div class="stat"><b>${totals.nope}</b><span>passed</span></div>
    </div>
  </div>`;

  const groups = TRAIT_GROUPS.map(([kind, title]) => {
    const entries = summary.traits[kind];
    if (!entries || entries.length === 0) return "";
    return `<div class="trait-group"><div class="trait-kind">${title}</div>${traitRows(entries, kind)}</div>`;
  }).join("");

  const tastePanel = `<div class="panel">
    <h2>What the algorithm has learned</h2>
    <p class="panel-sub">Confidence per trait — how strongly your swipes point at it.</p>
    ${groups || `<p class="profile-empty">Nothing yet — swipe a few cards and this fills in.</p>`}
  </div>`;

  const avoidPanel = summary.avoid.length
    ? `<div class="panel">
        <h2>Not your thing</h2>
        <p class="panel-sub">The feed pushes these down.</p>
        <div class="avoid-chips">${summary.avoid
          .map((a) => `<span class="chip">${traitLabel(a.kind, a.value)}</span>`)
          .join("")}</div>
      </div>`
    : "";

  const pickRows = picks
    .map(({ product, verdict }) => {
      const thumb = product.image
        ? `<img class="pick-img" src="${esc(product.image)}" alt="" loading="lazy" onerror="this.remove()" />`
        : "";
      return `<div class="pick">
        <span class="pick-emoji" style="background:${heroGradient(product)}">${product.emoji ?? "🛍"}${thumb}</span>
        <div class="pick-info">
          <p class="pick-title">${verdict === "love" ? `<span class="pick-love">★</span> ` : ""}<a
            class="pick-title-link" href="${esc(productUrl(product))}" target="_blank"
            rel="noopener noreferrer">${esc(product.title)}</a></p>
          <p class="pick-meta">${esc([product.brand, `$${product.price}`, platformLabel(product)].filter(Boolean).join(" · "))}</p>
        </div>
        <a class="pick-link" href="${esc(productUrl(product))}" target="_blank" rel="noopener noreferrer">
          Shop on ${esc(platformLabel(product).split(" ")[0])} ↗</a>
      </div>`;
    })
    .join("");

  const shortlistPanel = `<div class="panel">
    <h2>Your shortlist</h2>
    <p class="panel-sub">Everything you liked or starred.</p>
    ${pickRows || `<p class="profile-empty">Swipe right on something you’d actually buy and it lands here.</p>`}
  </div>`;

  const resetPanel = `<div class="panel">
    <h2>Start over</h2>
    <p class="panel-sub">Wipes every swipe and everything the algorithm has learned. There’s no undo.</p>
    <button type="button" class="btn btn-danger" id="reset-btn">Erase my profile</button>
  </div>`;

  body.innerHTML = statsPanel + tastePanel + avoidPanel + shortlistPanel + resetPanel;
  $("#reset-btn").addEventListener("click", resetProfile);
}

function resetProfile() {
  if (!confirm("Erase your entire shopping profile? This can’t be undone.")) return;
  profile = createProfile();
  clearProfile();
  deck = buildDeck(activeCatalog(), profile);
  renderStack();
  renderProfile();
  showTab("deck");
  toast("Fresh start — the algorithm knows nothing again");
}

// ---------------------------------------------------------------- tabs & app

function showTab(which) {
  $("#view-deck").hidden = which !== "deck";
  $("#view-profile").hidden = which !== "profile";
  $("#view-settings").hidden = which !== "settings";
  $("#tab-deck").classList.toggle("is-active", which === "deck");
  $("#tab-profile").classList.toggle("is-active", which === "profile");
  $("#tab-deck").setAttribute("aria-selected", String(which === "deck"));
  $("#tab-profile").setAttribute("aria-selected", String(which === "profile"));
  if (which === "profile") renderProfile();
}

let toastTimer = 0;
function toast(msg) {
  const el = $("#toast");
  el.textContent = msg;
  el.hidden = false;
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => (el.hidden = true), 2600);
}

function init() {
  renderStack();

  $("#tab-deck").addEventListener("click", () => showTab("deck"));
  $("#tab-profile").addEventListener("click", () => showTab("profile"));
  $("#settings-btn").addEventListener("click", () =>
    showTab($("#view-settings").hidden ? "settings" : "deck"));
  $("#settings-reset").addEventListener("click", resetProfile);
  $("#about-version").textContent = APP_VERSION;
  $("#about-updated").textContent = buildDateLabel();
  loadRealCatalog().then(() => startLiveFeed());
  $("#empty-to-profile").addEventListener("click", () => showTab("profile"));
  $("#empty-reset").addEventListener("click", resetProfile);

  $("#act-nope").addEventListener("click", () => commitSwipe("nope"));
  $("#act-like").addEventListener("click", () => commitSwipe("like"));
  $("#act-love").addEventListener("click", () => commitSwipe("love"));
  $("#act-undo").addEventListener("click", undo);

  $("#detail-close").addEventListener("click", closeDetail);
  $("#detail-backdrop").addEventListener("click", (e) => {
    if (e.target === e.currentTarget) closeDetail();
  });
  $("#detail-body").addEventListener("click", (e) => {
    const chip = e.target.closest(".chip[data-feature]");
    if (chip) {
      closeDetail();
      applyFilter(chip.dataset.feature, chip.textContent.trim());
    }
  });
  $("#filter-clear").addEventListener("click", clearFilter);
  $("#empty-clear-filter").addEventListener("click", clearFilter);

  document.addEventListener("keydown", (e) => {
    if (!$("#detail-backdrop").hidden) {
      if (e.key === "Escape") closeDetail();
      return; // arrows must not swipe while the detail sheet is open
    }
    if ($("#view-deck").hidden || e.metaKey || e.ctrlKey || e.altKey) return;
    if (e.key === "ArrowLeft") commitSwipe("nope");
    else if (e.key === "ArrowRight") commitSwipe("like");
    else if (e.key === "ArrowUp") { e.preventDefault(); commitSwipe("love"); }
    else if (e.key === "u" || e.key === "U") undo();
    else if ((e.key === "o" || e.key === "O") && deck[0]) {
      window.open(productUrl(deck[0]), "_blank", "noopener");
    }
  });
}

init();
